WebProje/WebProje/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebProje.DAL;
using WebProje.Models;
using PagedList;
using PagedList.Mvc;

namespace WebProje.Controllers
{
    [Authorize]
    public class UyeController : Controller
    {

        private VeriContext db = new VeriContext();

        // GET: Uye
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page/*int? SayfaNo*/)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.AdSortParm = String.IsNullOrEmpty(sortOrder) ? "AzalanAd" : "";
            ViewBag.SoyadSortParm = sortOrder == "Soyad" ? "AzalanSoyad" : "Soyad";
            ViewBag.KulAdiSortParm = sortOrder == "KulAdi" ? "AzalanKulAdi" : "KulAdi";
            ViewBag.EPostaSortParm = sortOrder == "EPosta" ? "AzalanEPosta" : "EPosta";
            ViewBag.SifreSortParm = sortOrder == "Sifre" ? "AzalanSifre" : "Sifre";
            ViewBag.UyelikTarihiSortParm = sortOrder == "UyelikTarihi" ? "AzalanUyelikTarihi" : "UyelikTarihi";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var uyeler = from s in db.Uyeler
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                uyeler = uyeler.Where(s => s.Ad.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Soyad":
                    uyeler = uyeler.OrderBy(s => s.Soyad);
                    break;
                case "AzalanSoyad":
                    uyeler = uyeler.OrderByDescending(s => s.Soyad);
                    break;
                case "KulAdi":
                    uyeler = uyeler.OrderBy(s => s.KulAdi);
                    break;
                case "AzalanKulAdi":
                    uyeler = uyeler.OrderByDescending(s => s.KulAdi);
                    break;
                case "EPosta":
                    uyeler = uyeler.OrderBy(s => s.EPosta);
                    break;
                case "AzalanEPosta":
                    uyeler = uyeler.OrderByDescending(s => s.EPosta);
                    break;
                case "Sifre":
                    uyeler = uyeler.OrderBy(s => s.Sifre);
                    break;
                case "AzalanSifre":
                    uyeler = uyeler.OrderByDescending(s => s.Sifre);
                    break;
                case "AzalanAd":
                    uyeler = uyeler.OrderByDescending(s => s.Ad);
                    break;
                case "UyelikTarihi":
                    uyeler = uyeler.OrderBy(s => s.UyelikTarihi);
                    break;
                case "AzalanUyelikTarihi":
                    uyeler = uyeler.OrderByDescending(s => s.UyelikTarihi);
                    break;
                default:  // Name ascending 
                    uyeler = uyeler.OrderBy(s => s.Ad);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(uyeler.ToPagedList(pageNumber, pageSize));
            /* int _sayfaNo = SayfaNo ?? 1;
             var uyeler = db.Uyeler.OrderByDescending(x => x.UyeID).ToPagedList<Uye>(_sayfaNo, 10);
             return View(uyeler);*/
        }

        // GET: Uye/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // GET: Uye/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Uye/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UyeID,Ad,Soyad,KulAdi,EPosta,Sifre,SifremiHatirla,GirisYapildiMi,UyelikTarihi")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Uyeler.Add(uye);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uye);
        }

        // GET: Uye/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: Uye/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UyeID,Ad,Soyad,KulAdi,EPosta,Sifre,SifremiHatirla,GirisYapildiMi,UyelikTarihi")] Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uye);
        }

        // GET: Uye/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyeler.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: Uye/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uye uye = db.Uyeler.Find(id);
            db.Uyeler.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebProje/WebProje/Views/Uye/Create.cshtml
@model WebProje.Models.Uye

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Uye</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KulAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KulAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KulAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EPosta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EPosta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EPosta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SifremiHatirla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.SifremiHatirla)
                    @Html.ValidationMessageFor(model => model.SifremiHatirla, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GirisYapildiMi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GirisYapildiMi)
                    @Html.ValidationMessageFor(model => model.GirisYapildiMi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UyelikTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UyelikTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UyelikTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebProje/WebProje/Views/Uye/Delete.cshtml
@model WebProje.Models.Uye

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Uye</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KulAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KulAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EPosta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EPosta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SifremiHatirla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifremiHatirla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GirisYapildiMi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GirisYapildiMi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyelikTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyelikTarihi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebProje/WebProje/Views/Uye/Details.cshtml
@model WebProje.Models.Uye

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Uye</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Soyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KulAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KulAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EPosta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EPosta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SifremiHatirla)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SifremiHatirla)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GirisYapildiMi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GirisYapildiMi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UyelikTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UyelikTarihi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UyeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebProje/WebProje/Views/Uye/Edit.cshtml
@model WebProje.Models.Uye

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Uye</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UyeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KulAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KulAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KulAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EPosta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EPosta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EPosta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SifremiHatirla, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.SifremiHatirla)
                    @Html.ValidationMessageFor(model => model.SifremiHatirla, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GirisYapildiMi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GirisYapildiMi)
                    @Html.ValidationMessageFor(model => model.GirisYapildiMi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UyelikTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UyelikTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UyelikTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@WebProje.Resources.Kaynak.Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink(@WebProje.Resources.Kaynak.ListeyeDon, "Index")
</div>

WebProje/WebProje/Views/Uye/Index.cshtml
@using PagedList
@using PagedList.Mvc
@using WebProje.Models
@model IPagedList<Uye>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>@WebProje.Resources.Kaynak.UyelerListesi</h2>

    <p>
        @Html.ActionLink(@WebProje.Resources.Kaynak.YeniUye, "Create", null, new { @class = "btn btn-primary btn-large" })
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.UyeAdi, "Index", new { sortOrder = ViewBag.AdSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.Soyadi, "Index", new { sortOrder = ViewBag.SoyadSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.KullaniciAdi, "Index", new { sortOrder = ViewBag.KulAdiSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.EPosta, "Index", new { sortOrder = ViewBag.EPostaSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.Sifre, "Index", new { sortOrder = ViewBag.SifreSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @WebProje.Resources.Kaynak.SifremiHatirla
            </th>
            <th>
                @WebProje.Resources.Kaynak.GirisYapildiMi
            </th>
            <th>
                @Html.ActionLink(@WebProje.Resources.Kaynak.UyelikTarihi, "Index", new { sortOrder = ViewBag.UyelikTarihiSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Soyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KulAdi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EPosta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sifre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SifremiHatirla)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GirisYapildiMi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UyelikTarihi)
                </td>
                <td>
                    @Html.ActionLink(@WebProje.Resources.Kaynak.Duzenle, "Edit", new { id = item.UyeID }, new { @class = "btn btn-primary btn-large" }) |
                    @Html.ActionLink(@WebProje.Resources.Kaynak.Detaylar, "Details", new { id = item.UyeID }, new { @class = "btn btn-primary btn-large" }) |
                    @Html.ActionLink(@WebProje.Resources.Kaynak.Sil, "Delete", new { id = item.UyeID }, new { @class = "btn btn-primary btn-large" })
                </td>
            </tr>
        }

    </table>

    @Html.PagedListPager(Model, page => Url.Action("Index", "Uye", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))